#https://github.com/cloudnative-pg/cloudnative-pg/blob/main/docs/src/samples/cluster-example-full.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: kobimate-pg
  namespace: default
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2-5-bookworm
  imagePullPolicy: IfNotPresent
  bootstrap:
  #initdb:
  #    postInitTemplateSQL:
  #      - CREATE EXTENSION postgis;
  #      - CREATE EXTENSION postgis_topology;
  #      - CREATE EXTENSION fuzzystrmatch;
  #      - CREATE EXTENSION postgis_tiger_geocoder;
  postgresql:
    parameters:
      shared_buffers: 256MB
      pg_stat_statements.max: '10000'
      pg_stat_statements.track: all
      auto_explain.log_min_duration: '10s'
  enableSuperuserAccess: true
  superuserSecret:
    name: pg-super-user
  storage:
    size: 5Gi