apiVersion: apps/v1
kind: Deployment
metadata:
  name: kobimate-odoo18
  namespace: default
  labels:
    app: odoo18-paket-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kobimate-odoo18
  template:
    metadata:
      labels:
        app: kobimate-odoo18
    spec:
      imagePullSecrets:
        - name: git-sync-secret
      containers:
        - name: kobimate-odoo18
          image: ghcr.io/kobimate/odoo:18.0-latest
          imagePullPolicy: IfNotPresent
          env:
            #Database connection configuration
            - name: DB_HOST
              value: kobimate-pg-rw
            - name: DB_REPLICA_HOST
              value: kobimate-pg-r
            - name: DB_NAME
              value: odoo18
            - name: DB_PASSWORD 
              value: "8639159"
            - name: DB_USER
              value: odoo
            - name: LIST_DB
              value: "true"
            - name: ADMIN_PASSWD
              value: "$pbkdf2-sha512$25000$Vuq919pbq7XW2tubsxZibA$1G82RkbAGJuADzQ8sCvWtj9287UeLqmhal5agD1n73oQOP8L6yy2ZJhTiDs.ESy/HWiAVC9AxTLkNLMy9jgeoA"
            - name: WORKERS
              value: "2"
          ports:
            - containerPort: 8069
          volumeMounts:
            - name: odoo18-kobimate-volume
              mountPath: /data/odoo
          terminationGracePeriodSeconds: 0

      volumes:
        - name: odoo18-kobimate-volume
          persistentVolumeClaim:
            claimName: kobimate-odoo18-pvc