apiVersion: apps/v1
kind: Deployment
metadata:
  name: kobimate-odoo18
  namespace: default
  labels:
    app: odoo18-paket-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kobimate-odoo18
  template:
    metadata:
      labels:
        app: kobimate-odoo18
    spec:
      #imagePullSecrets:
      #  - name: git-sync-secret
      containers:
        - name: kobimate-odoo18
          image: odoo:18
          imagePullPolicy: Always
          env:
            #Database connection configuration
            - name: HOST
              value: my-cluster-rw
            - name: PASSWORD 
              value: n8YzEJz79Qun3TV5PsmGPbMDBwHC91Ihn5U3AxWcAnTsGvR1xEmGbQvsISjgMDAU
            - name: USER
              value: app
          ports:
            - containerPort: 8069
          volumeMounts:
            - name: odoo18-kobimate-volume
              mountPath: /mnt/extra-addons

      volumes:
        - name: odoo18-kobimate-volume
          persistentVolumeClaim:
            claimName: kobimate-odoo18-pvc
