apiVersion: apps/v1
kind: Deployment
metadata:
  name: kobimate-odoo18
  namespace: default
  labels:
    app: odoo18-paket-1
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kobimate-odoo18
  template:
    metadata:
      labels:
        app: kobimate-odoo18
    spec:
      imagePullSecrets:
        - name: git-sync-secret
      containers:
        - name: kobimate-odoo18
          image: ghcr.io/kobimate/odoo:18.0-latest
          imagePullPolicy: Always
          env:
            #Database connection configuration
            - name: DB_HOST
              value: kobimate-pg-rw
            - name: DB_REPLICA_HOST
              value: kobimate-pg-r
            - name: DB_NAME
              value: odoo18
            - name: DB_PASSWORD 
              value: "8639159"
            - name: DB_USER
              value: odoo
            - name: LIST_DB
              value: "true"
            - name: ADMIN_PASSWD
              value: "$pbkdf2-sha512$25000$Vuq919pbq7XW2tubsxZibA$1G82RkbAGJuADzQ8sCvWtj9287UeLqmhal5agD1n73oQOP8L6yy2ZJhTiDs.ESy/HWiAVC9AxTLkNLMy9jgeoA"
            - name: ODOO_SESSION_REDIS
              value: "1"
            - name: ODOO_SESSION_REDIS_HOST
              value: "argocd-redis-ha"
            - name: ODOO_SESSION_REDIS_PORT
              value: "6379"
            - name: ODOO_SESSION_REDIS_PASSWORD
              value: "EG95ErbDpxt4t01g"
            - name: ODOO_SESSION_REDIS_PREFIX
              value: "odoo18"

            - name: SERVER_WIDE_MODULES
              value: "web,session_redis"
          ports:
            - containerPort: 8069
          volumeMounts:
            - name: odoo18-kobimate-volume
              mountPath: /data/odoo
      terminationGracePeriodSeconds: 30
      volumes:
        - name: odoo18-kobimate-volume
          persistentVolumeClaim:
            claimName: kobimate-odoo18-pvc