apiVersion: apps/v1
kind: Deployment
metadata:
  name: kobimate-odoo18
  namespace: default
  labels:
    app: odoo18-paket-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kobimate-odoo18
  template:
    metadata:
      labels:
        app: kobimate-odoo18
    spec:
      #imagePullSecrets:
      #  - name: git-sync-secret
      containers:
        - name: kobimate-odoo18
          image:ghcr.io/acsone/odoo-bedrock:17.0-py311-jammy-latest
          imagePullPolicy: IfNotPresent
          env:
            #Database connection configuration
            - name: DB_HOST
              value: my-cluster-r
            - name: DB_REPLICA_HOST
              value: my-cluster-rw
            - name: DB_NAME
              value: odoo18
            - name: DB_PASSWORD 
              value: 9WWVJTGEtMtCM4ARqoQPKP8ic0gmSlNlwVpVI9fkopqkvjfvJ4E94HswU28KNGXG
            - name: DB_USER
              value: app
          ports:
            - containerPort: 8069
          volumeMounts:
            - name: odoo18-kobimate-volume
              mountPath: /data/odoo

      volumes:
        - name: odoo18-kobimate-volume
          persistentVolumeClaim:
            claimName: kobimate-odoo18-pvc
