apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kobimate-odoo18-ingress
  namespace: argocd
spec:
  rules:
  - host: odoo18.kobimate.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: kobimate-odoo18-service
            port:
              number: 8069