apiVersion: v1
kind: Service
metadata:
  name: odoo18-service
spec:
  type: ClusterIP
  ports:
    - name: {{ .Values.appname }}
      port: 8069
      protocol: TCP
      targetPort: 8069
    - name: websocket
      port: 8072
      protocol: TCP
      targetPort: 8072
  selector:
    app: kobimate-odoo18
  