apiVersion: v1
kind: Service
metadata:
  name: kobimate-odoo18-service
  namespace: argocd
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8069
  selector:
    app: kobimate-odoo18