apiVersion: v1
kind: Service
metadata:
  name: kobimate-odoo18-service
spec:
  type: ClusterIP  
  ports:
    - name: odoo_http
      port: 80
      targetPort: 8069
    - name: odoo_https
      port: 443
      targetPort: 8069
    - name: longpolling
      port: 8072
  selector:
    app: kobimate-odoo18