apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Chart.AppVersion }}-{{ .Values.app_name }}-pvc"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-sc
  resources:
    requests:
      storage: 5Gi