apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.AppVersion }}-{{ .Values.app_name }}-service"
spec:
  type: ClusterIP
  ports:
    - name: {{ .Values.appname }}
      port: {{ .Values.ports.web }}
      protocol: TCP
      targetPort: {{ .Values.ports.web }}
    - name: websocket
      port: {{ .Values.ports.websocket }}
      protocol: TCP
      targetPort: {{ .Values.ports.websocket }}
  selector:
    app: "{{ .Chart.AppVersion }}-{{ .Values.app_name }}"
  