apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guest-book
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: odoo18
    repoURL: https://github.com/esakarya/test.git
    targetRevision: HEAD