#https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odoo-18-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: odoo18
    repoURL: https://github.com/esakarya/test.git
    targetRevision: HEAD
    plugin:
     # If the plugin is defined as a sidecar and name is not passed, the plugin will be automatically matched with the
     # Application according to the plugin's discovery rules.
     name: mypluginname
     # environment variables passed to the plugin
     env:
       - name: FOO
         value: bar
     # Plugin parameters are new in v2.5.
     parameters:
       - name: string-param
         string: example-string
       - name: array-param
         array: [item1, item2]
       - name: map-param
         map:
           param-name: param-value