#https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odoo-18-ap
  namespace: argocd
  inputs:
      parameters:
      - name: app-name
      - name: app-image
      - name: app-env
      - name: app-replicas
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: odoo18
    repoURL: https://github.com/esakarya/test.git
    targetRevision: HEAD

