apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: b2bpoke
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/esakarya/test
    path: odoo-18
    targetRevision: HEAD
    helm:
      parameters:
        -name: app_name
         value: b2bpoke
        -name: host
         value: b2bpoke.kobimate.com
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    #syncOptions:
    #  - CreateNamespace=true